language: elixir
matrix:
  include:
  - otp_release: 18.0
    elixir: 1.5.0
  - otp_release: 21.2
    elixir: 1.7.4
  - otp_release: 21.3
    elixir: 1.8.2
  - otp_release: 22.3
    elixir: 1.9.4
  - otp_release: 22.3
    elixir: 1.10.4
  - otp_release: 23.1
    elixir: 1.11.1
sudo: false # to use faster container based build environment
cache:
  directories:
    - _build
    - deps
